import * as cheerio from "cheerio";
import fs from "fs";
const html=fs.readFileSync("/tmp/grok_rendered.html","utf8");
const $=cheerio.load(html);
console.log("user-msg:", $('[data-testid="user-message"]').length);
console.log("ast-msg:", $('[data-testid="assistant-message"]').length);
const u=$('[data-testid="user-message"]').first();
const a=$('[data-testid="assistant-message"]').first();
console.log("--- first user text (300c) ---");
console.log(u.text().slice(0,300));
console.log("--- first user .message-bubble html (400c) ---");
console.log((u.find(".message-bubble").first().html()||u.html()||"").slice(0,400));
console.log("--- first assistant .response-content-markdown html (400c) ---");
const md=a.find(".response-content-markdown").first();
console.log((md.html()||"").slice(0,400));
console.log("--- response-content-markdown total ---");
console.log($(".response-content-markdown").length);
console.log("--- title ---");
console.log($("title").text());
