import { useEffect } from "react";
import { Link } from "wouter";
import { Layout } from "@/components/Layout";
import { ContentPage } from "@/components/ContentPage";
import { SITE_URL, useSEO } from "@/lib/seo";

interface QA {
  q: string;
  a: string;
}

const FAQ: QA[] = [
  {
    q: "Is ChatScribe free?",
    a: "Yes. ChatScribe is completely free to use. There's no signup, no paywall, and no usage limits.",
  },
  {
    q: "Do I need to log in?",
    a: "No. The tool only works with public share links, so there is nothing to authenticate.",
  },
  {
    q: "Do you store the conversations I extract?",
    a: "No. Every request is processed in memory and discarded. We do not save the share URL, the parsed conversation, or any user-identifying metadata.",
  },
  {
    q: "Which AI platforms are supported?",
    a: "ChatGPT (chatgpt.com / chat.openai.com), Claude (claude.ai), Gemini (gemini.google.com), Grok (grok.com / x.com), and DeepSeek. See the Supported Platforms page for URL formats.",
  },
  {
    q: "What output formats can I download?",
    a: "Markdown (.md), plain text (.txt), and PDF (.pdf). You can also copy the full conversation as Markdown to your clipboard with one click.",
  },
  {
    q: "Can I extract a private or unshared conversation?",
    a: "No. ChatScribe only works with public share links generated by the chat platform itself. If a link requires sign-in or returns 404 in an incognito window, we can't read it either.",
  },
  {
    q: "Why did my Grok / Claude / Gemini link fail to parse?",
    a: "Most extraction failures happen because (a) the link was deleted or made private, (b) the platform changed its page structure recently, or (c) the share is on an unsupported sub-product. If a previously working link suddenly fails, the platform likely updated their HTML; please report it and we'll patch the parser.",
  },
  {
    q: "Are long conversations supported?",
    a: "Yes. The extractor waits for the full transcript to render before parsing, so very long threads come through complete.",
  },
  {
    q: "Are images, code, and tables preserved?",
    a: "Code blocks, ordered/unordered lists, tables, and inline formatting are preserved as Markdown. Images that were generated or uploaded inside the share are referenced by URL where the platform exposes them.",
  },
  {
    q: "Is this affiliated with OpenAI, Anthropic, Google, xAI, or DeepSeek?",
    a: "No. ChatScribe is an independent tool. All product names and trademarks belong to their respective owners.",
  },
];

export default function Faq() {
  useSEO({
    title: "FAQ — Frequently Asked Questions",
    description:
      "Answers to common questions about ChatScribe: pricing, privacy, supported platforms, output formats, and troubleshooting failed extractions.",
    path: "/faq",
    keywords:
      "chat extractor faq, free chatgpt extractor, save ai conversations, export claude chat, ai chat to pdf",
  });

  // FAQPage structured data — Google's rich-result format for FAQs.
  useEffect(() => {
    const ld = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: FAQ.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    };
    const script = document.createElement("script");
    script.type = "application/ld+json";
    script.id = "faq-jsonld";
    script.text = JSON.stringify(ld);
    document.head.appendChild(script);
    return () => {
      document.getElementById("faq-jsonld")?.remove();
    };
  }, []);

  return (
    <Layout>
      <ContentPage
        eyebrow="Help"
        title="Frequently asked questions"
        intro="Answers to the most common questions about ChatScribe. Don't see yours? Check the How It Works guide."
      >
        {FAQ.map((f) => (
          <section key={f.q}>
            <h2>{f.q}</h2>
            <p>{f.a}</p>
          </section>
        ))}

        <h2>Still stuck?</h2>
        <p>
          Read the <Link href="/how-it-works">How It Works</Link> guide or learn
          more <Link href="/about">about the project</Link>. You can also visit
          the <a href={SITE_URL}>home page</a> and try a fresh link.
        </p>
      </ContentPage>
    </Layout>
  );
}
